#ifndef _KBROGUE_CONFIG_HEADER_IN_
#define _KBROGUE_CONFIG_HEADER_IN_

#define KBROGUE_VERSION_TYPE "develop"
#define KBROGUE_VERSION_MAJOR 0
#define KBROGUE_VERSION_MINOR 0

#endif // _KBROGUE_CONFIG_HEADER_IN_
